### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by emilymye**

### CODE REVIEW

**Comment by jefferai** [comment]
Any reason you switched the Vault dep from master to 0.9.0?

**Comment by emilymye** [comment]
Not sure since I just ran the dep tool but I'll fix it.

**Comment by emilymye** [comment]
This should be ready to go

**Comment by jefferai** [comment]
Cool -- I don't normally check dep updates carefully but I do look at changes to the toml file and that struck me as odd. I may at release time change things to a specific branch for reasons of pulling-into-vault's-codebase-for-compiling-in but since release always comes from master generally that'll be the right thing at the time anyways :-)

**Pull request merged**
