### PR TITLE
Automated dependency upgrades

### PR DESCRIPTION
**Pull request by hc-github-team-secure-vault-ecosystem**
Full log: https://github.com/hashicorp/vault-plugin-auth-gcp/actions/runs/8707230961

  IMPROVEMENTS:
* Updated dependencies:
   * `cloud.google.com/go/compute/metadata` v0.2.3 -> v0.3.0
   * `github.com/hashicorp/go-hclog` v1.6.2 -> v1.6.3
   * `github.com/hashicorp/vault/api` v1.11.0 -> v1.12.2
   * `github.com/hashicorp/vault/sdk` v0.10.2 -> v0.12.0
   * `github.com/stretchr/testify` v1.8.4 -> v1.9.0
   * `golang.org/x/oauth2` v0.16.0 -> v0.19.0
   * `google.golang.org/api` v0.161.0 -> v0.172.0

### CODE REVIEW

**Comment by hc-github-team-secure-vault-core** [comment]
Vault CI check PR: https://github.com/hashicorp/vault/pull/26224

**Comment by hc-github-team-secure-vault-core** [comment]
Vault CI check PR: https://github.com/hashicorp/vault/pull/26224

**Comment by hc-github-team-secure-vault-core** [comment]
Vault CI check PR: https://github.com/hashicorp/vault/pull/26224

**Review by tomhjp — APPROVED** [review]

**Comment by tvoran** [comment]
Oh I bet this needs `make mocks` run before it'll work with the new vault libs.

**Comment by tomhjp** [comment]
@tvoran yep spot on, thanks for the pointer. I opened #199 to merge into this PR before merging into main. If you get a chance I'd love a quick review from a second pair of eyes.

**Comment by tomhjp** [comment]
I'm not sure what went wrong with the automated Vault PR so I did a manual successful CI run here: https://github.com/hashicorp/vault/actions/runs/8742345488

**Pull request merged**
